// <auto-generated />
using System;
using LinkwayAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LinkwayAPI.Migrations
{
    [DbContext(typeof(LinkwayDbContext))]
    [Migration("20250611152549_coreconnectmigration")]
    partial class coreconnectmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LinkwayAPI.Data.UsrUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("About")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("BannerPhotoName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("BusinessUnitId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DesignationId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("EmergencyContactNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeCode"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedInUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePhotoName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PronounId")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkypeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessUnitId");

                    b.HasIndex("DesignationId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("PronounId");

                    b.ToTable("AspNetUsers", null, t =>
                        {
                            t.HasTrigger("TRG_AspNetUsers_Delete");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("LinkwayAPI.Models.CndGiftform", b =>
                {
                    b.Property<int>("GiftformId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GIFTFormId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GiftformId"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<string>("CareerGrowthContribution")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<int>("CurrentDesignationId")
                        .HasColumnType("int");

                    b.Property<int>("DesiredDesignationId")
                        .HasColumnType("int");

                    b.Property<string>("EndResult")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("GapsIdentified")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("GiftformAdminStatus")
                        .HasColumnType("int")
                        .HasColumnName("GIFTFormAdminStatus");

                    b.Property<Guid>("GiftformGuid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GIFTFormGuid");

                    b.Property<int>("GiftformManagerStatus")
                        .HasColumnType("int")
                        .HasColumnName("GIFTFormManagerStatus");

                    b.Property<string>("GiftformRejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("GIFTFormRejectionReason");

                    b.Property<int?>("GiftformReviewerId")
                        .HasColumnType("int")
                        .HasColumnName("GIFTFormReviewerId");

                    b.Property<bool>("IsSupportRequired")
                        .HasColumnType("bit");

                    b.Property<string>("LearningAndTransistionProcess")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("MajorAchievements")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PlanOfAction")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("TargetAchievementDate")
                        .HasColumnType("datetime");

                    b.Property<string>("WorkRelatedTrainingAndCertifications")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("GiftformId");

                    b.HasIndex("CandidateId");

                    b.HasIndex("CurrentDesignationId");

                    b.HasIndex("DesiredDesignationId");

                    b.HasIndex("GiftformReviewerId");

                    b.HasIndex(new[] { "GiftformGuid" }, "IX_CND_GIFTForms")
                        .IsUnique();

                    b.ToTable("CND_GIFTForms", (string)null);
                });

            modelBuilder.Entity("LinkwayAPI.Models.MstBusinessUnit", b =>
                {
                    b.Property<int>("BusinessUnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BusinessUnitId"));

                    b.Property<string>("BusinessUnitDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("BusinessUnitGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusinessUnitLogoName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BusinessUnitName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime");

                    b.HasKey("BusinessUnitId");

                    b.HasIndex(new[] { "BusinessUnitGuid" }, "IX_MST_BusinessUnits")
                        .IsUnique();

                    b.ToTable("MST_BusinessUnits", (string)null);
                });

            modelBuilder.Entity("LinkwayAPI.Models.MstCause", b =>
                {
                    b.Property<int>("CauseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CauseId"));

                    b.Property<string>("Cause")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CauseDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("CauseGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime");

                    b.HasKey("CauseId");

                    b.HasIndex(new[] { "CauseGuid" }, "IX_MST_Causes")
                        .IsUnique();

                    b.ToTable("MST_Causes", (string)null);
                });

            modelBuilder.Entity("LinkwayAPI.Models.MstCertification", b =>
                {
                    b.Property<int>("CertificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CertificationId"));

                    b.Property<string>("CertificationDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("CertificationGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CertificationTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime");

                    b.HasKey("CertificationId");

                    b.ToTable("MST_Certifications", (string)null);
                });

            modelBuilder.Entity("LinkwayAPI.Models.MstCompany", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("CompanyDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("CompanyGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime");

                    b.HasKey("CompanyId");

                    b.HasIndex(new[] { "CompanyGuid" }, "IX_MST_Companies")
                        .IsUnique();

                    b.ToTable("MST_Companies", (string)null);
                });

            modelBuilder.Entity("LinkwayAPI.Models.MstDepartment", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DepartmentDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("DepartmentGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime");

                    b.HasKey("DepartmentId");

                    b.HasIndex(new[] { "DepartmentGuid" }, "IX_MST_Departments")
                        .IsUnique();

                    b.ToTable("MST_Departments", (string)null);
                });

            modelBuilder.Entity("LinkwayAPI.Models.MstDesignation", b =>
                {
                    b.Property<int>("DesignationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DesignationId"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DesignationDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("DesignationGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DesignationLevel")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime");

                    b.HasKey("DesignationId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex(new[] { "DesignationGuid" }, "IX_MST_Designations")
                        .IsUnique();

                    b.ToTable("MST_Designations", (string)null);
                });

            modelBuilder.Entity("LinkwayAPI.Models.MstEmploymentType", b =>
                {
                    b.Property<int>("EmploymentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmploymentTypeId"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("EmploymentTypeDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("EmploymentTypeGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmploymentTypeTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime");

                    b.HasKey("EmploymentTypeId");

                    b.HasIndex(new[] { "EmploymentTypeGuid" }, "IX_MST_EmploymentTypes")
                        .IsUnique();

                    b.ToTable("MST_EmploymentTypes", (string)null);
                });

            modelBuilder.Entity("LinkwayAPI.Models.MstInternalProgram", b =>
                {
                    b.Property<int>("InternalProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InternalProgramId"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<int>("InternalProgramActiveDays")
                        .HasColumnType("int");

                    b.Property<string>("InternalProgramDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("InternalProgramGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InternalProgramName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("InternalProgramReviewCycle")
                        .HasColumnType("int");

                    b.Property<bool>("IsInternalProgramCategoryExists")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime");

                    b.HasKey("InternalProgramId");

                    b.HasIndex(new[] { "InternalProgramGuid" }, "IX_MST_InternalPrograms")
                        .IsUnique();

                    b.ToTable("MST_InternalPrograms", (string)null);
                });

            modelBuilder.Entity("LinkwayAPI.Models.MstInternalProgramCategory", b =>
                {
                    b.Property<int>("InternalProgramCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InternalProgramCategoryId"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("InternalProgramCategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("InternalProgramCategoryDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("InternalProgramCategoryGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("InternalProgramId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime");

                    b.HasKey("InternalProgramCategoryId");

                    b.HasIndex("InternalProgramId");

                    b.HasIndex(new[] { "InternalProgramCategoryGuid" }, "IX_MST_InternalProgramCategories")
                        .IsUnique();

                    b.ToTable("MST_InternalProgramCategories", (string)null);
                });

            modelBuilder.Entity("LinkwayAPI.Models.MstLocationType", b =>
                {
                    b.Property<int>("LocationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationTypeId"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LocationTypeDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("LocationTypeGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime");

                    b.HasKey("LocationTypeId");

                    b.HasIndex(new[] { "LocationTypeGuid" }, "IX_MST_LocationTypes")
                        .IsUnique();

                    b.ToTable("MST_LocationTypes", (string)null);
                });

            modelBuilder.Entity("LinkwayAPI.Models.MstNotification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsNotificationRead")
                        .HasColumnType("bit")
                        .HasColumnName("isNotificationRead");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("NotificationDescription")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("NotificationGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NotificationTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "NotificationGuid" }, "IX_MST_Notifications")
                        .IsUnique();

                    b.ToTable("MST_Notifications", (string)null);
                });

            modelBuilder.Entity("LinkwayAPI.Models.MstProficiency", b =>
                {
                    b.Property<int>("ProficiencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProficiencyId"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ProficiencyDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ProficiencyGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProficiencyTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProficiencyId");

                    b.HasIndex(new[] { "ProficiencyGuid" }, "IX_MST_Proficiencies")
                        .IsUnique();

                    b.ToTable("MST_Proficiencies", (string)null);
                });

            modelBuilder.Entity("LinkwayAPI.Models.MstProject", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ProjectDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ProjectGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProjectTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProjectId");

                    b.HasIndex(new[] { "ProjectGuid" }, "IX_MST_Projects")
                        .IsUnique();

                    b.ToTable("MST_Projects", (string)null);
                });

            modelBuilder.Entity("LinkwayAPI.Models.MstPronoun", b =>
                {
                    b.Property<int>("PronounId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PronounId"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Pronoun")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PronounDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("PronounGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PronounId")
                        .HasName("PK_MST_Pronounses");

                    b.HasIndex(new[] { "PronounGuid" }, "IX_MST_Pronouns")
                        .IsUnique();

                    b.ToTable("MST_Pronouns", (string)null);
                });

            modelBuilder.Entity("LinkwayAPI.Models.MstSkill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillId"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("SkillDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("SkillGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SkillTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SkillId");

                    b.HasIndex(new[] { "SkillGuid" }, "IX_MST_Skills")
                        .IsUnique();

                    b.ToTable("MST_Skills", (string)null);
                });

            modelBuilder.Entity("LinkwayAPI.Models.MstTraining", b =>
                {
                    b.Property<int>("TrainingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainingId"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("TrainingDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TrainingGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TrainingTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TrainingId");

                    b.ToTable("MST_Trainings", (string)null);
                });

            modelBuilder.Entity("LinkwayAPI.Models.MstTrainingType", b =>
                {
                    b.Property<int>("TrainingTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainingTypeId"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("TrainingType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrainingTypeDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TrainingTypeGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TrainingTypeId");

                    b.HasIndex(new[] { "TrainingTypeGuid" }, "IX_MST_TrainingTypes")
                        .IsUnique();

                    b.ToTable("MST_TrainingTypes", (string)null);
                });

            modelBuilder.Entity("LinkwayAPI.Models.NmsAttachment", b =>
                {
                    b.Property<int>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttachmentId"));

                    b.Property<Guid>("AttachmentGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttachmentName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime");

                    b.Property<int>("NominationId")
                        .HasColumnType("int");

                    b.HasKey("AttachmentId");

                    b.HasIndex("NominationId");

                    b.HasIndex(new[] { "AttachmentGuid" }, "IX_NMS_Attachments")
                        .IsUnique();

                    b.ToTable("NMS_Attachments", (string)null);
                });

            modelBuilder.Entity("LinkwayAPI.Models.NmsNomination", b =>
                {
                    b.Property<int>("NominationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NominationId"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<int>("CycleIteration")
                        .HasColumnType("int");

                    b.Property<int?>("InternalProgramCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("InternalProgramId")
                        .HasColumnType("int");

                    b.Property<string>("JustificationComment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("NominationGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NominationRejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("NominationStatus")
                        .HasColumnType("int");

                    b.Property<int>("NominatorId")
                        .HasColumnType("int");

                    b.Property<int>("NomineeId")
                        .HasColumnType("int");

                    b.HasKey("NominationId");

                    b.HasIndex("InternalProgramCategoryId");

                    b.HasIndex("InternalProgramId");

                    b.HasIndex("NominatorId");

                    b.HasIndex("NomineeId");

                    b.HasIndex(new[] { "NominationGuid" }, "IX_NMS_Nominations")
                        .IsUnique();

                    b.ToTable("NMS_Nominations", (string)null);
                });

            modelBuilder.Entity("LinkwayAPI.Models.RstRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime");

                    b.Property<int>("NoOfMembers")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime");

                    b.Property<string>("RequestDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("RequestGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RequestRejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RequestStatus")
                        .HasColumnType("int");

                    b.Property<int>("RequestType")
                        .HasColumnType("int");

                    b.Property<int>("RequesterId")
                        .HasColumnType("int");

                    b.HasKey("RequestId")
                        .HasName("PK_RST_Request");

                    b.HasIndex("RequesterId");

                    b.HasIndex(new[] { "RequestGuid" }, "IX_RST_Requests")
                        .IsUnique();

                    b.ToTable("RST_Requests", (string)null);
                });

            modelBuilder.Entity("LinkwayAPI.Models.UsrAward", b =>
                {
                    b.Property<int>("AwardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AwardId"));

                    b.Property<string>("AwardDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("AwardGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AwardIssueDate")
                        .HasColumnType("datetime");

                    b.Property<string>("AwardIssuer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AwardPhotoName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AwardTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AwardId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "AwardGuid" }, "IX_USR_Awards")
                        .IsUnique();

                    b.ToTable("USR_Awards", (string)null);
                });

            modelBuilder.Entity("LinkwayAPI.Models.UsrCertification", b =>
                {
                    b.Property<int>("UserCertificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserCertificationId"));

                    b.Property<int>("CertificateIssuingCompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CertificationCredentialId")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("CertificationCredentialUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("CertificationCredentialURL");

                    b.Property<string>("CertificationDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CertificationExpirationDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("CertificationGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CertificationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CertificationIssueDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CertificationPhotoName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserCertificationId")
                        .HasName("PK_EMP_Certificates");

                    b.HasIndex("CertificateIssuingCompanyId");

                    b.HasIndex("CertificationId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "CertificationGuid" }, "IX_USR_Certificates")
                        .IsUnique();

                    b.ToTable("USR_Certifications", (string)null);
                });

            modelBuilder.Entity("LinkwayAPI.Models.UsrComment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("CommentGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CommenterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CommentId")
                        .HasName("PK_EMP_Comments");

                    b.HasIndex("CommenterId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "CommentGuid" }, "IX_USR_Comments")
                        .IsUnique();

                    b.ToTable("USR_Comments", (string)null);
                });

            modelBuilder.Entity("LinkwayAPI.Models.UsrEducation", b =>
                {
                    b.Property<int>("EducationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EducationId"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("EducationDegree")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EducationDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("EducationEndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("EducationGrade")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("EducationGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EducationInstituteName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("EducationStartDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsEducationActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("EducationId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "EducationGuid" }, "IX_USR_Educations")
                        .IsUnique();

                    b.ToTable("USR_Educations", (string)null);
                });

            modelBuilder.Entity("LinkwayAPI.Models.UsrExperience", b =>
                {
                    b.Property<int>("ExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExperienceId"));

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<int>("DesignationId")
                        .HasColumnType("int");

                    b.Property<int?>("EmploymentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ExperienceDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ExperienceEndDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("ExperienceGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExperienceStartDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsExperienceActive")
                        .HasColumnType("bit");

                    b.Property<int?>("LocationTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ExperienceId")
                        .HasName("PK_EMP_Experience");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DesignationId");

                    b.HasIndex("EmploymentTypeId");

                    b.HasIndex("LocationTypeId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "ExperienceGuid" }, "IX_USR_Experiences")
                        .IsUnique();

                    b.ToTable("USR_Experiences", (string)null);
                });

            modelBuilder.Entity("LinkwayAPI.Models.UsrKra", b =>
                {
                    b.Property<int>("Kraid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KRAId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Kraid"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Kradescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("KRADescription");

                    b.Property<Guid>("Kraguid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("KRAGuid");

                    b.Property<string>("Kratitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("KRATitle");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Kraid");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "Kraguid" }, "IX_USR_KRAs")
                        .IsUnique();

                    b.ToTable("USR_KRAs", (string)null);
                });

            modelBuilder.Entity("LinkwayAPI.Models.UsrLanguage", b =>
                {
                    b.Property<int>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LanguageId"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("LanguageGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("ProficiencyId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LanguageId");

                    b.HasIndex("ProficiencyId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "LanguageGuid" }, "IX_USR_Languages")
                        .IsUnique();

                    b.ToTable("USR_Languages", (string)null);
                });

            modelBuilder.Entity("LinkwayAPI.Models.UsrPatent", b =>
                {
                    b.Property<int>("PatentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatentId"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PatentApplicationNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PatentDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("PatentGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PatentIssueDate")
                        .HasColumnType("datetime");

                    b.Property<int>("PatentStatus")
                        .HasColumnType("int");

                    b.Property<string>("PatentTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PatentUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("PatentURL");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PatentId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "PatentGuid" }, "IX_USR_Patents")
                        .IsUnique();

                    b.ToTable("USR_Patents", (string)null);
                });

            modelBuilder.Entity("LinkwayAPI.Models.UsrProject", b =>
                {
                    b.Property<int>("UserProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserProjectId"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsProjectActive")
                        .HasColumnType("bit")
                        .HasColumnName("isProjectActive");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ProjectDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ProjectEndDate")
                        .HasColumnType("datetime");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ProjectStartDate")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserProjectGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserProjectId")
                        .HasName("PK_EMP_Projects");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "UserProjectGuid" }, "IX_USR_Projects")
                        .IsUnique();

                    b.ToTable("USR_Projects", (string)null);
                });

            modelBuilder.Entity("LinkwayAPI.Models.UsrSkill", b =>
                {
                    b.Property<int>("UserSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserSkillId"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("ProficiencyId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserSkillGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserSkillId");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "UserSkillGuid" }, "IX_USR_Skills")
                        .IsUnique();

                    b.ToTable("USR_Skills", (string)null);
                });

            modelBuilder.Entity("LinkwayAPI.Models.UsrTraining", b =>
                {
                    b.Property<int>("UserTrainingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserTrainingId"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsTrainingActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("TrainingEndDate")
                        .HasColumnType("datetime");

                    b.Property<int>("TrainingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TrainingStartDate")
                        .HasColumnType("datetime");

                    b.Property<int>("TrainingTypeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserTrainingDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserTrainingGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserTrainingId")
                        .HasName("PK_EMP_Trainings");

                    b.HasIndex("TrainingId");

                    b.HasIndex("TrainingTypeId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "UserTrainingGuid" }, "IX_USR_Trainings")
                        .IsUnique();

                    b.ToTable("USR_Trainings", (string)null);
                });

            modelBuilder.Entity("LinkwayAPI.Models.UsrVolunteeringExperience", b =>
                {
                    b.Property<int>("VolunteeringExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VolunteeringExperienceId"));

                    b.Property<int?>("CauseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsVolunteeringExperienceActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("VolunteeringExperienceDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("VolunteeringExperienceEndDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("VolunteeringExperienceGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VolunteeringExperienceOrganization")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VolunteeringExperienceRole")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("VolunteeringExperienceStartDate")
                        .HasColumnType("datetime");

                    b.HasKey("VolunteeringExperienceId");

                    b.HasIndex("CauseId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "VolunteeringExperienceGuid" }, "IX_USR_VolunteeringExperiences")
                        .IsUnique();

                    b.ToTable("USR_VolunteeringExperiences", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RelCertificationsSkill", b =>
                {
                    b.Property<int>("CertificationId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("CertificationId", "SkillId")
                        .HasName("PK_REL_CertificationsSkills_1");

                    b.HasIndex("SkillId");

                    b.ToTable("REL_CertificationsSkills", (string)null);
                });

            modelBuilder.Entity("RelRequestsUser", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RequestId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("REL_RequestsUsers", (string)null);
                });

            modelBuilder.Entity("RelUserProjectsSkill", b =>
                {
                    b.Property<int>("UserProjectId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("UserProjectId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("REL_UserProjectsSkills", (string)null);
                });

            modelBuilder.Entity("LinkwayAPI.Data.UsrUser", b =>
                {
                    b.HasOne("LinkwayAPI.Models.MstBusinessUnit", "BusinessUnit")
                        .WithMany("AspNetUsers")
                        .HasForeignKey("BusinessUnitId");

                    b.HasOne("LinkwayAPI.Models.MstDesignation", "Designation")
                        .WithMany("UsrUsers")
                        .HasForeignKey("DesignationId");

                    b.HasOne("LinkwayAPI.Models.MstPronoun", "Pronoun")
                        .WithMany("UsrUsers")
                        .HasForeignKey("PronounId");

                    b.Navigation("BusinessUnit");

                    b.Navigation("Designation");

                    b.Navigation("Pronoun");
                });

            modelBuilder.Entity("LinkwayAPI.Models.CndGiftform", b =>
                {
                    b.HasOne("LinkwayAPI.Data.UsrUser", "Candidate")
                        .WithMany("CndGiftformCandidates")
                        .HasForeignKey("CandidateId")
                        .HasPrincipalKey("EmployeeCode")
                        .IsRequired()
                        .HasConstraintName("FK_CND_GIFTForms_CND_GIFTForms");

                    b.HasOne("LinkwayAPI.Models.MstDesignation", "CurrentDesignation")
                        .WithMany("CndGiftformCurrentDesignations")
                        .HasForeignKey("CurrentDesignationId")
                        .IsRequired()
                        .HasConstraintName("FK_CND_GIFTForms_MST_Designations");

                    b.HasOne("LinkwayAPI.Models.MstDesignation", "DesiredDesignation")
                        .WithMany("CndGiftformDesiredDesignations")
                        .HasForeignKey("DesiredDesignationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CND_GIFTForms_MST_Designations1");

                    b.HasOne("LinkwayAPI.Data.UsrUser", "GiftformReviewer")
                        .WithMany("CndGiftformGiftformReviewers")
                        .HasForeignKey("GiftformReviewerId")
                        .HasPrincipalKey("EmployeeCode")
                        .HasConstraintName("FK_CND_GIFTForms_AspNetUsers");

                    b.Navigation("Candidate");

                    b.Navigation("CurrentDesignation");

                    b.Navigation("DesiredDesignation");

                    b.Navigation("GiftformReviewer");
                });

            modelBuilder.Entity("LinkwayAPI.Models.MstDesignation", b =>
                {
                    b.HasOne("LinkwayAPI.Models.MstDepartment", "Department")
                        .WithMany("MstDesignations")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MST_Designations_MST_Departments");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("LinkwayAPI.Models.MstInternalProgramCategory", b =>
                {
                    b.HasOne("LinkwayAPI.Models.MstInternalProgram", "InternalProgram")
                        .WithMany("MstInternalProgramCategories")
                        .HasForeignKey("InternalProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MST_InternalProgramCategories_MST_InternalPrograms");

                    b.Navigation("InternalProgram");
                });

            modelBuilder.Entity("LinkwayAPI.Models.MstNotification", b =>
                {
                    b.HasOne("LinkwayAPI.Data.UsrUser", "User")
                        .WithMany("MstNotifications")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("EmployeeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MST_Notifications_AspNetUsers");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LinkwayAPI.Models.NmsAttachment", b =>
                {
                    b.HasOne("LinkwayAPI.Models.NmsNomination", "Nomination")
                        .WithMany("NmsAttachments")
                        .HasForeignKey("NominationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_NMS_Attachments_NMS_Nominations");

                    b.Navigation("Nomination");
                });

            modelBuilder.Entity("LinkwayAPI.Models.NmsNomination", b =>
                {
                    b.HasOne("LinkwayAPI.Models.MstInternalProgramCategory", "InternalProgramCategory")
                        .WithMany("NmsNominations")
                        .HasForeignKey("InternalProgramCategoryId")
                        .HasConstraintName("FK_NMS_Nominations_MST_InternalProgramCategories");

                    b.HasOne("LinkwayAPI.Models.MstInternalProgram", "InternalProgram")
                        .WithMany("NmsNominations")
                        .HasForeignKey("InternalProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_NMS_Nominations_MST_InternalPrograms");

                    b.HasOne("LinkwayAPI.Data.UsrUser", "Nominator")
                        .WithMany("NmsNominationNominators")
                        .HasForeignKey("NominatorId")
                        .HasPrincipalKey("EmployeeCode")
                        .IsRequired()
                        .HasConstraintName("FK_NMS_Nominations_AspNetUsers");

                    b.HasOne("LinkwayAPI.Data.UsrUser", "Nominee")
                        .WithMany("NmsNominationNominees")
                        .HasForeignKey("NomineeId")
                        .HasPrincipalKey("EmployeeCode")
                        .IsRequired()
                        .HasConstraintName("FK_NMS_Nominations_AspNetUsersNominee");

                    b.Navigation("InternalProgram");

                    b.Navigation("InternalProgramCategory");

                    b.Navigation("Nominator");

                    b.Navigation("Nominee");
                });

            modelBuilder.Entity("LinkwayAPI.Models.RstRequest", b =>
                {
                    b.HasOne("LinkwayAPI.Data.UsrUser", "Requester")
                        .WithMany("RstRequests")
                        .HasForeignKey("RequesterId")
                        .HasPrincipalKey("EmployeeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RST_Requests_AspNetUsers");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("LinkwayAPI.Models.UsrAward", b =>
                {
                    b.HasOne("LinkwayAPI.Data.UsrUser", "User")
                        .WithMany("UsrAwards")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("EmployeeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_USR_Awards_AspNetUsers");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LinkwayAPI.Models.UsrCertification", b =>
                {
                    b.HasOne("LinkwayAPI.Models.MstCompany", "CertificateIssuingCompany")
                        .WithMany("UsrCertifications")
                        .HasForeignKey("CertificateIssuingCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_USR_Certifications_MST_Companies");

                    b.HasOne("LinkwayAPI.Models.MstCertification", "Certification")
                        .WithMany("UsrCertifications")
                        .HasForeignKey("CertificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_USR_Certifications_MST_Certifications");

                    b.HasOne("LinkwayAPI.Data.UsrUser", "User")
                        .WithMany("UsrCertifications")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("EmployeeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_USR_Certifications_AspNetUsers");

                    b.Navigation("CertificateIssuingCompany");

                    b.Navigation("Certification");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LinkwayAPI.Models.UsrComment", b =>
                {
                    b.HasOne("LinkwayAPI.Data.UsrUser", "Commenter")
                        .WithMany("UsrCommentCommenters")
                        .HasForeignKey("CommenterId")
                        .HasPrincipalKey("EmployeeCode")
                        .IsRequired()
                        .HasConstraintName("FK_USR_Comments_AspNetUsers");

                    b.HasOne("LinkwayAPI.Data.UsrUser", "User")
                        .WithMany("UsrCommentUsers")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("EmployeeCode")
                        .IsRequired()
                        .HasConstraintName("FK_USR_Comments_AspNetUsersEmployee");

                    b.Navigation("Commenter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LinkwayAPI.Models.UsrEducation", b =>
                {
                    b.HasOne("LinkwayAPI.Data.UsrUser", "User")
                        .WithMany("UsrEducations")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("EmployeeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_USR_Educations_AspNetUsers");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LinkwayAPI.Models.UsrExperience", b =>
                {
                    b.HasOne("LinkwayAPI.Models.MstCompany", "Company")
                        .WithMany("UsrExperiences")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_USR_Experiences_MST_Companies");

                    b.HasOne("LinkwayAPI.Models.MstDesignation", "Designation")
                        .WithMany("UsrExperiences")
                        .HasForeignKey("DesignationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_USR_Experiences_MST_Designations");

                    b.HasOne("LinkwayAPI.Models.MstEmploymentType", "EmploymentType")
                        .WithMany("UsrExperiences")
                        .HasForeignKey("EmploymentTypeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_EMP_Experience_MST_EmploymentTypes");

                    b.HasOne("LinkwayAPI.Models.MstLocationType", "LocationType")
                        .WithMany("UsrExperiences")
                        .HasForeignKey("LocationTypeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_USR_Experiences_MST_LocationTypes");

                    b.HasOne("LinkwayAPI.Data.UsrUser", "User")
                        .WithMany("UsrExperiences")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("EmployeeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_USR_Experiences_AspNetUsers");

                    b.Navigation("Company");

                    b.Navigation("Designation");

                    b.Navigation("EmploymentType");

                    b.Navigation("LocationType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LinkwayAPI.Models.UsrKra", b =>
                {
                    b.HasOne("LinkwayAPI.Data.UsrUser", "User")
                        .WithMany("UsrKras")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("EmployeeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_USR_KRAs_AspNetUsers");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LinkwayAPI.Models.UsrLanguage", b =>
                {
                    b.HasOne("LinkwayAPI.Models.MstProficiency", "Proficiency")
                        .WithMany("UsrLanguages")
                        .HasForeignKey("ProficiencyId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_USR_Languages_MST_Proficiencies");

                    b.HasOne("LinkwayAPI.Data.UsrUser", "User")
                        .WithMany("UsrLanguages")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("EmployeeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_USR_Languages_AspNetUsers");

                    b.Navigation("Proficiency");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LinkwayAPI.Models.UsrPatent", b =>
                {
                    b.HasOne("LinkwayAPI.Data.UsrUser", "User")
                        .WithMany("UsrPatents")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("EmployeeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_USR_Patents_AspNetUsers");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LinkwayAPI.Models.UsrProject", b =>
                {
                    b.HasOne("LinkwayAPI.Models.MstProject", "Project")
                        .WithMany("UsrProjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_USR_Projects_MST_Projects");

                    b.HasOne("LinkwayAPI.Data.UsrUser", "User")
                        .WithMany("UsrProjects")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("EmployeeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_USR_Projects_AspNetUsers");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LinkwayAPI.Models.UsrSkill", b =>
                {
                    b.HasOne("LinkwayAPI.Models.MstSkill", "Skill")
                        .WithMany("UsrSkills")
                        .HasForeignKey("SkillId")
                        .IsRequired()
                        .HasConstraintName("FK_USR_Skills_MST_Skills");

                    b.HasOne("LinkwayAPI.Data.UsrUser", "User")
                        .WithMany("UsrSkills")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("EmployeeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_USR_Skills_AspNetUsers");

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LinkwayAPI.Models.UsrTraining", b =>
                {
                    b.HasOne("LinkwayAPI.Models.MstTraining", "Training")
                        .WithMany("UsrTrainings")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_USR_Trainings_MST_Trainings");

                    b.HasOne("LinkwayAPI.Models.MstTrainingType", "TrainingType")
                        .WithMany("UsrTrainings")
                        .HasForeignKey("TrainingTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EMP_Trainings_MST_TrainingTypes");

                    b.HasOne("LinkwayAPI.Data.UsrUser", "User")
                        .WithMany("UsrTrainings")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("EmployeeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_USR_Trainings_AspNetUsers");

                    b.Navigation("Training");

                    b.Navigation("TrainingType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LinkwayAPI.Models.UsrVolunteeringExperience", b =>
                {
                    b.HasOne("LinkwayAPI.Models.MstCause", "Cause")
                        .WithMany("UsrVolunteeringExperiences")
                        .HasForeignKey("CauseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_USR_VolunteeringExperiences_MST_Causes");

                    b.HasOne("LinkwayAPI.Data.UsrUser", "User")
                        .WithMany("UsrVolunteeringExperiences")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("EmployeeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_USR_VolunteeringExperiences_AspNetUsers");

                    b.Navigation("Cause");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LinkwayAPI.Data.UsrUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LinkwayAPI.Data.UsrUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinkwayAPI.Data.UsrUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LinkwayAPI.Data.UsrUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RelCertificationsSkill", b =>
                {
                    b.HasOne("LinkwayAPI.Models.UsrCertification", null)
                        .WithMany()
                        .HasForeignKey("CertificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_REL_CertificationsSkills_USR_Certifications");

                    b.HasOne("LinkwayAPI.Models.MstSkill", null)
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_REL_CertificationsSkills_MST_Skills");
                });

            modelBuilder.Entity("RelRequestsUser", b =>
                {
                    b.HasOne("LinkwayAPI.Models.RstRequest", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_REL_RequestsUsers_RST_Requests");

                    b.HasOne("LinkwayAPI.Data.UsrUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("EmployeeCode")
                        .IsRequired()
                        .HasConstraintName("FK_REL_RequestsUsers_AspNetUsers");
                });

            modelBuilder.Entity("RelUserProjectsSkill", b =>
                {
                    b.HasOne("LinkwayAPI.Models.MstSkill", null)
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_REL_UserProjectsSkills_MST_Skills");

                    b.HasOne("LinkwayAPI.Models.UsrProject", null)
                        .WithMany()
                        .HasForeignKey("UserProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_REL_UserProjectsSkills_USR_Projects");
                });

            modelBuilder.Entity("LinkwayAPI.Data.UsrUser", b =>
                {
                    b.Navigation("CndGiftformCandidates");

                    b.Navigation("CndGiftformGiftformReviewers");

                    b.Navigation("MstNotifications");

                    b.Navigation("NmsNominationNominators");

                    b.Navigation("NmsNominationNominees");

                    b.Navigation("RstRequests");

                    b.Navigation("UsrAwards");

                    b.Navigation("UsrCertifications");

                    b.Navigation("UsrCommentCommenters");

                    b.Navigation("UsrCommentUsers");

                    b.Navigation("UsrEducations");

                    b.Navigation("UsrExperiences");

                    b.Navigation("UsrKras");

                    b.Navigation("UsrLanguages");

                    b.Navigation("UsrPatents");

                    b.Navigation("UsrProjects");

                    b.Navigation("UsrSkills");

                    b.Navigation("UsrTrainings");

                    b.Navigation("UsrVolunteeringExperiences");
                });

            modelBuilder.Entity("LinkwayAPI.Models.MstBusinessUnit", b =>
                {
                    b.Navigation("AspNetUsers");
                });

            modelBuilder.Entity("LinkwayAPI.Models.MstCause", b =>
                {
                    b.Navigation("UsrVolunteeringExperiences");
                });

            modelBuilder.Entity("LinkwayAPI.Models.MstCertification", b =>
                {
                    b.Navigation("UsrCertifications");
                });

            modelBuilder.Entity("LinkwayAPI.Models.MstCompany", b =>
                {
                    b.Navigation("UsrCertifications");

                    b.Navigation("UsrExperiences");
                });

            modelBuilder.Entity("LinkwayAPI.Models.MstDepartment", b =>
                {
                    b.Navigation("MstDesignations");
                });

            modelBuilder.Entity("LinkwayAPI.Models.MstDesignation", b =>
                {
                    b.Navigation("CndGiftformCurrentDesignations");

                    b.Navigation("CndGiftformDesiredDesignations");

                    b.Navigation("UsrExperiences");

                    b.Navigation("UsrUsers");
                });

            modelBuilder.Entity("LinkwayAPI.Models.MstEmploymentType", b =>
                {
                    b.Navigation("UsrExperiences");
                });

            modelBuilder.Entity("LinkwayAPI.Models.MstInternalProgram", b =>
                {
                    b.Navigation("MstInternalProgramCategories");

                    b.Navigation("NmsNominations");
                });

            modelBuilder.Entity("LinkwayAPI.Models.MstInternalProgramCategory", b =>
                {
                    b.Navigation("NmsNominations");
                });

            modelBuilder.Entity("LinkwayAPI.Models.MstLocationType", b =>
                {
                    b.Navigation("UsrExperiences");
                });

            modelBuilder.Entity("LinkwayAPI.Models.MstProficiency", b =>
                {
                    b.Navigation("UsrLanguages");
                });

            modelBuilder.Entity("LinkwayAPI.Models.MstProject", b =>
                {
                    b.Navigation("UsrProjects");
                });

            modelBuilder.Entity("LinkwayAPI.Models.MstPronoun", b =>
                {
                    b.Navigation("UsrUsers");
                });

            modelBuilder.Entity("LinkwayAPI.Models.MstSkill", b =>
                {
                    b.Navigation("UsrSkills");
                });

            modelBuilder.Entity("LinkwayAPI.Models.MstTraining", b =>
                {
                    b.Navigation("UsrTrainings");
                });

            modelBuilder.Entity("LinkwayAPI.Models.MstTrainingType", b =>
                {
                    b.Navigation("UsrTrainings");
                });

            modelBuilder.Entity("LinkwayAPI.Models.NmsNomination", b =>
                {
                    b.Navigation("NmsAttachments");
                });
#pragma warning restore 612, 618
        }
    }
}
