const API_BASE_URL = 'http://localhost:5289';

export const environment = {
  production: false,
  apiUrl: `${API_BASE_URL}/api`,
  imageUrl: `${API_BASE_URL}/resources`,
  roles: {
    user: '/user',
    admin: '/admin',
  },
  routes: {
    dashboard: '/dashboard',
    management: '/management',
    candidate: '/candidate',
    basicDetails: '/basic-details',
    deleteavatar: '/avatar/delete',
    avatar: '/avatar',
    businessUnits: '/business-units',
    certificates: '/certificates',
    getAll: '/get-all',
    comments: '/comments',
    experiences: '/experiences',
    employmentTypes: '/employment-types',
    giftForms: '/gift-forms',
    internalprogram: '/internalprogram',
    certifications: '/certifications',
    internalprogramcategory: '/internal-programs-categories',
    kras: '/kras',
    languages: '/languages',
    workModels: '/work-models',
    users: '/users',
    nominations: '/nominations',
    proficiency: '/proficiency',
    projects: '/projects',
    pronouns: '/pronouns',
    requests: '/requests',
    skills: '/skills',
    trainings: '/trainings',
    getAllByUserId: '/get-all-by-userId',
    profileStrength: '/profile-strength',
    accounts: '/accounts',
    login: '/login',
    signUp: '/signUp',
    forgotPassword: '/forgot-password',
    resetPasword: '/reset-password',
    changePassword: '/change-password',
    search: '/search',
    designation: '/designation',
    department: '/department',
    companies: '/companies',
    project: '/project',
    notifications: "/notifications"
  },
  actions: {
    update: '/update',
    delete: '/delete',
    approve: '/approve',
    reject: '/reject',
  },
  queryParams: {
    pageNumber: 'pageNumber',
    pageSize: 'pageSize',
    pageIndex: 'pageIndex',
    userId: 'userId',
  },
};
